name: Master Workflow

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup and Install
        uses: ./.github/actions/setup

      - name: Run linter
        run: npm run lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup and Install
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: npm test

  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup and Install
        uses: ./.github/actions/setup

      - name: Build application
        run: npm run build
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=10x-project --branch=main
